import {test,expect,type Page} from "@playwright/test";
const fixture="http://127.0.0.1:54329/fixtures",tutor="00000000-0000-4000-8000-000000000002",student="00000000-0000-4000-8000-000000000004";
async function login(page:Page,role="admin"){await page.goto("/login");await page.getByLabel("Логин",{exact:true}).fill(role);await page.getByLabel("Пароль",{exact:true}).fill("fixture-password");await page.getByRole("button",{name:"Войти",exact:true}).click();await expect(page).toHaveURL(`/${role}/schedule`,{timeout:15000});}
test.beforeEach(async({request})=>{await request.post(fixture+"/reset-schedule");await request.post(fixture+"/applications-reset");});
test("020 admin directory has inset search and long heading wraps",async({page})=>{
 await login(page);await page.goto(`/admin/chats?tutor=${tutor}&student=${student}`);
 for(const width of [1440,375,320]){await page.setViewportSize({width,height:900});const search=await page.locator(".chat-search").boundingBox(),directory=await page.locator(".chat-directory").boundingBox();expect(search!.y).toBeGreaterThan(directory!.y);await page.locator(".chat-heading h2").evaluate(el=>el.textContent="ОченьДлинноеИмяБезПробелов".repeat(3));expect(await page.locator(".chat-heading").evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/020-admin-chat-${width}.png`,fullPage:true});}
});
test("020 background covers section edges and site motion respects reduced motion",async({page})=>{
 await login(page);await page.getByRole("button",{name:"Фон",exact:true}).click();await page.getByLabel("Загрузить / заменить").setInputFiles({name:"background.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=","base64")});await expect(page.getByText("Фон сохранён.",{exact:true})).toBeVisible();await page.keyboard.press("Escape");
 for(const width of [1440,375]){await page.setViewportSize({width,height:900});const section=await page.locator(".dashboard-content").boundingBox(),bg=await page.locator(".schedule-background").boundingBox();for(const key of ["x","y","width","height"] as const)expect(Math.abs(section![key]-bg![key])).toBeLessThan(1);await page.screenshot({path:`artifacts/020-background-${width}.png`,fullPage:true});}
 expect(await page.locator(".site-background i").first().evaluate(el=>getComputedStyle(el).animationName)).toBe("site-drift");await page.emulateMedia({reducedMotion:"reduce"});expect(await page.locator(".site-background i").first().evaluate(el=>getComputedStyle(el).animationName)).toBe("none");await page.goto("/admin/settings");await expect(page.locator(".site-background")).toBeVisible();expect(await page.locator(".support-fab").evaluate(el=>getComputedStyle(el).position)).toBe("fixed");
});
test("020 settings persist packages, custom macros/libraries and compile previews through action",async({page})=>{
 await login(page);await page.goto("/admin/settings");await page.getByLabel("Пакеты LaTeX",{exact:true}).fill("amsmath, amssymb, tikz, asymptote, booktabs, custom");await page.getByLabel("Преамбула и команды",{exact:true}).fill(String.raw`\newcommand{\R}{\mathbb{R}}`);
 await page.getByLabel("Добавить библиотеки LaTeX",{exact:true}).setInputFiles({name:"custom.sty",mimeType:"text/plain",buffer:Buffer.from(String.raw`\ProvidesPackage{custom}`)});await page.getByRole("button",{name:"Сохранить LaTeX",exact:true}).click();await expect(page.getByText("Настройки LaTeX сохранены.",{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel("Пакеты LaTeX",{exact:true})).toHaveValue("amsmath, amssymb, tikz, asymptote, booktabs, custom");await expect(page.getByLabel("Преамбула и команды",{exact:true})).toHaveValue(String.raw`\newcommand{\R}{\mathbb{R}}`);await expect(page.getByRole("button",{name:"Удалить custom.sty",exact:true})).toBeVisible();await page.getByRole("button",{name:"Сохранить и проверить",exact:true}).click();await expect(page.getByAltText("Результат компиляции LaTeX",{exact:true})).toBeVisible();await page.setViewportSize({width:375,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:"artifacts/020-settings.png",fullPage:true});
 await page.goto(`/admin/chats?tutor=${tutor}`);await expect(page.getByRole("heading",{name:"Чаты репетитора",exact:true})).toBeVisible();
});
test("020 chat recognizes native Asymptote environment and can request a raster preview",async({page})=>{
 await login(page,"tutor");await page.goto(`/tutor/chats?student=${student}`);await page.getByLabel("Сообщение ученику",{exact:true}).fill("\\begin{asy}\ndraw(unitsquare);\n\\end{asy}");await page.locator(".chat-live-preview").getByRole("button",{name:"Отобразить LaTeX",exact:true}).click();await expect(page.locator(".chat-live-preview").getByAltText("Рисунок LaTeX",{exact:true})).toBeVisible();
});
