import {test,expect,type Page} from "@playwright/test";
async function login(page:Page){await page.goto("/login");await page.getByLabel("Логин",{exact:true}).fill("admin");await page.getByLabel("Пароль",{exact:true}).fill("fixture-password");await page.getByRole("button",{name:"Войти",exact:true}).click();await expect(page).toHaveURL("/admin/schedule",{timeout:15000});}
test("021 real browser TikZ and Asymptote render without a compiler service",async({page})=>{
 test.setTimeout(90000);await login(page);await page.goto("/admin/settings");await expect(page.getByLabel("Преамбула и команды",{exact:true})).toHaveCount(0);
 const calls:string[]=[];page.on("request",r=>{if(r.url().includes("latex-render"))calls.push(r.url());});
 await page.getByRole("button",{name:"Отобразить LaTeX",exact:true}).click();await expect(page.getByAltText("Рисунок LaTeX",{exact:true})).toBeVisible({timeout:30000});const tikz=await page.getByAltText("Рисунок LaTeX",{exact:true}).getAttribute("src");expect(tikz).toContain("data:image/svg+xml");expect(decodeURIComponent(tikz!)).toContain("<path");await page.screenshot({path:"artifacts/021-tikz.png",fullPage:true});
 await page.getByLabel("Код для проверки LaTeX",{exact:true}).fill("\\begin{asy}\nsize(250);pair A=(0,0),B=(2,1);draw(A--B,red+Arrow);draw(circle((1,0),0.5));label(\"Привет\",(1,1.4));\n\\end{asy}");await page.getByRole("button",{name:"Отобразить LaTeX",exact:true}).click();await expect(page.getByAltText("Рисунок LaTeX",{exact:true})).toBeVisible();const asy=decodeURIComponent((await page.getByAltText("Рисунок LaTeX",{exact:true}).getAttribute("src"))!);expect(asy).toContain("Привет");expect(asy).toContain("<circle");expect(calls).toEqual([]);await page.screenshot({path:"artifacts/021-asy.png",fullPage:true});
});
test("021 background animates, reacts gently and stops with reduced motion",async({page})=>{
 await page.goto("/login");await expect(page.locator(".site-background")).toBeVisible();await expect(page.locator(".site-particle")).toHaveCount(12);await page.mouse.move(100,100);await expect.poll(()=>page.locator(".site-background").evaluate(el=>el.style.getPropertyValue("--drift-x"))).not.toBe("");await page.screenshot({path:"artifacts/021-login.png",fullPage:true});await login(page);await page.goto("/admin/settings");await page.emulateMedia({reducedMotion:"reduce"});expect(await page.locator(".site-orbit").first().evaluate(el=>getComputedStyle(el).animationName)).toBe("none");await page.setViewportSize({width:375,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test("021 infinite TikZ execution is terminated without freezing the page",async({page})=>{
 test.setTimeout(45000);await login(page);await page.goto("/admin/settings");await page.getByLabel("Код для проверки LaTeX",{exact:true}).fill(String.raw`\begin{tikzpicture}\loop\iftrue\repeat\end{tikzpicture}`);await page.getByRole("button",{name:"Отобразить LaTeX",exact:true}).click();await page.getByLabel("Код для проверки LaTeX",{exact:true}).focus();await expect(page.getByLabel("Код для проверки LaTeX",{exact:true})).toBeFocused();await expect(page.locator(".compiled-latex-view [role=alert]")).toContainText("слишком сложный",{timeout:25000});
});
