import {test,expect,type Page} from "@playwright/test";
const fixture="http://127.0.0.1:54329/fixtures",tutor="00000000-0000-4000-8000-000000000002",student="00000000-0000-4000-8000-000000000004";
async function login(page:Page,role="tutor"){await page.goto("/login");await page.getByLabel("Логин",{exact:true}).fill(role);await page.getByLabel("Пароль",{exact:true}).fill("fixture-password");await page.getByRole("button",{name:"Войти",exact:true}).click();await expect(page).toHaveURL(`/${role}/schedule`,{timeout:15000});}
async function selectWord(page:Page,word:string){await page.getByLabel("Сообщение ученику",{exact:true}).evaluate((el,word)=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const i=node.textContent!.indexOf(word);if(i<0)continue;const range=document.createRange();range.setStart(node,i);range.setEnd(node,i+word.length);el.focus();const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);return;}throw new Error("Word not found");},word);}
test.beforeEach(async({request})=>{await request.post(fixture+"/reset-schedule");await request.post(fixture+"/applications-reset");});
test("019 formatting follows selected words and alignment is mutually exclusive",async({page})=>{
 await login(page);await page.goto(`/tutor/chats?student=${student}`);const input=page.getByLabel("Сообщение ученику",{exact:true});await expect(input).toHaveAttribute("contenteditable","true");await input.focus();await input.evaluate(el=>{const d=new DataTransfer();d.setData("text/html",'<p><b><i><u><s>Alpha</s></u></i></b> plain</p><p style="text-align:right">Right</p><p style="text-align:center">Center</p>');el.dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:d}));});
 await selectWord(page,"Alpha");for(const name of ["Жирный","Курсив","Подчёркивание","Зачёркивание"])await expect(page.getByRole("button",{name,exact:true})).toHaveAttribute("aria-pressed","true");
 await selectWord(page,"plain");for(const name of ["Жирный","Курсив","Подчёркивание","Зачёркивание"])await expect(page.getByRole("button",{name,exact:true})).toHaveAttribute("aria-pressed","false");
 await selectWord(page,"Right");await expect(page.getByRole("button",{name:"По правому краю",exact:true})).toHaveAttribute("aria-pressed","true");await page.getByRole("button",{name:"По центру",exact:true}).click();await expect(page.getByRole("button",{name:"По правому краю",exact:true})).toHaveAttribute("aria-pressed","false");await expect(page.getByRole("button",{name:"По центру",exact:true})).toHaveAttribute("aria-pressed","true");
 await page.getByRole("button",{name:"Отменить",exact:true}).click();await selectWord(page,"Right");await expect(page.getByRole("button",{name:"По правому краю",exact:true})).toHaveAttribute("aria-pressed","true");await page.screenshot({path:"artifacts/019-formatting.png",fullPage:true});
});
test("019 MSK resets incomplete input without error layout; formula limits are not clipped",async({page})=>{
 await login(page);const offset=page.getByLabel("Сдвиг МСК",{exact:true});for(const value of ["","-","+"]){await offset.fill(value);await offset.press("Enter");await expect(offset).toHaveValue("0");await expect(page.locator(".schedule-offset .field-error")).toHaveCount(0);}await page.setViewportSize({width:375,height:900});await page.screenshot({path:"artifacts/019-offset.png",fullPage:true});
 await page.goto(`/tutor/chats?student=${student}`);await page.getByLabel("Сообщение ученику",{exact:true}).fill(String.raw`$\displaystyle\max_{x\in[0,1]} f(x)=1$`);const math=page.locator(".chat-live-preview .chat-math");await expect(math.locator(".katex")).toBeVisible();expect(await math.evaluate(el=>getComputedStyle(el).overflowY)).toBe("visible");
 for(const width of [375,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/019-formula-${width}.png`,fullPage:true});}
});
test("019 multi-selection disables pair operations and removes reserved colors",async({page})=>{
 await login(page,"admin");await page.setViewportSize({width:1440,height:1000});await page.goto(`/admin/schedule?tutor=${tutor}`);const box=(await page.locator(".schedule-grid").boundingBox())!;
 await page.mouse.move(box.x+1,box.y+box.height*9/24);await page.mouse.down();await page.mouse.move(box.x+box.width/7-1,box.y+box.height*14/24,{steps:8});await page.mouse.up();await expect(page.locator('.schedule-lesson[aria-pressed="true"]')).toHaveCount(2);await page.locator('.schedule-lesson[aria-pressed="true"]').first().click({button:"right"});
 for(const name of ["Перенести…","Заниматься с…","Личное"])await expect(page.getByRole("menuitem",{name,exact:true})).toBeDisabled();for(const name of ["Зелёный","Голубой"])await expect(page.getByRole("menuitemradio",{name,exact:true})).toHaveCount(0);await expect(page.getByRole("menuitemradio")).toHaveCount(3);await page.screenshot({path:"artifacts/019-menu.png",fullPage:true});
});
test("019 GIF has no file row, MP4 plays, admin opens teacher history and private media",async({page,browser})=>{
 test.setTimeout(60000);await login(page);await page.goto(`/tutor/chats?student=${student}`);
 await page.locator('input[type="file"]').setInputFiles({name:"animation.gif",mimeType:"image/gif",buffer:Buffer.from("R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","base64")});await page.getByRole("button",{name:"Отправить",exact:true}).click();await expect(page.locator(".chat-bubble img")).toBeVisible();await expect(page.locator(".chat-bubble .chat-file-row")).toHaveCount(0);
 const bytes=await page.evaluate(async()=>{const c=document.createElement("canvas");c.width=c.height=64;const stream=c.captureStream(10),r=new MediaRecorder(stream,{mimeType:"video/mp4"}),chunks:Blob[]=[];r.ondataavailable=e=>chunks.push(e.data);const done=new Promise<Blob>(resolve=>{r.onstop=()=>resolve(new Blob(chunks));});r.start();c.getContext("2d")!.fillRect(0,0,64,64);await new Promise(resolve=>setTimeout(resolve,350));r.stop();const blob=await done;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await blob.arrayBuffer())];});
 await page.locator('input[type="file"]').setInputFiles({name:"preview.mp4",mimeType:"video/mp4",buffer:Buffer.from(bytes)});await expect(page.locator(".chat-draft-file video")).toBeVisible();await page.getByRole("button",{name:"Отправить",exact:true}).click();await expect(page.locator(".chat-bubble video")).toBeVisible();await expect.poll(()=>page.locator(".chat-bubble video").evaluate((el:HTMLVideoElement)=>el.readyState)).toBeGreaterThanOrEqual(1);
 const admin=await browser.newPage();try{await login(admin,"admin");await admin.goto("/admin/tutors");await admin.getByRole("link",{name:"Чаты: Мария Соколова",exact:true}).click();await expect(admin).toHaveURL(new RegExp(`tutor=${tutor}`));await expect(admin.getByRole("heading",{name:"Чаты репетитора",exact:true})).toBeVisible();await expect(admin.locator(".chat-bubble video")).toBeVisible();await expect.poll(()=>admin.locator(".chat-bubble video").evaluate((el:HTMLVideoElement)=>el.readyState)).toBeGreaterThanOrEqual(1);await expect(admin.getByRole("button",{name:"Отправить",exact:true})).toHaveCount(0);await admin.screenshot({path:"artifacts/019-admin-chat.png",fullPage:true});await admin.setViewportSize({width:375,height:900});expect(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await admin.screenshot({path:"artifacts/019-admin-chat-mobile.png",fullPage:true});}finally{await admin.close();}
});
