import {test,expect,type Page} from "@playwright/test";
import {gzipSync} from "node:zlib";
const fixture="http://127.0.0.1:54329/fixtures",tutor="00000000-0000-4000-8000-000000000002",student="00000000-0000-4000-8000-000000000004";
async function login(page:Page,role="tutor"){await page.goto("/login");await page.getByLabel("Логин",{exact:true}).fill(role);await page.getByLabel("Пароль",{exact:true}).fill("fixture-password");await page.getByRole("button",{name:"Войти",exact:true}).click();await expect(page).toHaveURL(`/${role}/schedule`);}
test.beforeEach(async({request})=>{await request.post(fixture+"/reset-schedule");await request.post(fixture+"/applications-reset");});
test("018 administrator tutor/pair rates fix completion history",async({page,request})=>{
 await login(page,"admin");await page.goto("/admin/tutors");const row=page.locator(".person-row").filter({hasText:"Мария Соколова"});await row.getByRole("button",{name:"Ставка",exact:true}).click();await page.getByLabel("Ставка, ₽/час",{exact:true}).fill("1700");await page.getByRole("button",{name:"Сохранить",exact:true}).click();
 await expect(page.getByRole("dialog")).toHaveCount(0);await page.goto(`/admin/schedule?tutor=${tutor}`);const lesson=page.locator('.schedule-lesson[data-lesson-id="00000000-0000-4000-8000-000000000100"]');await lesson.click({button:"right"});await page.getByRole("menuitem",{name:"Личное",exact:true}).click();await page.getByLabel("Ставка, ₽/час",{exact:true}).fill("1900.01");await page.getByRole("button",{name:"Сохранить",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 await lesson.click({button:"right"});await page.getByRole("menuitem",{name:"Отметить проведёнными",exact:true}).click();await expect.poll(async()=>{const state=await(await request.get(fixture+"/state")).json();return state.lessons[0].hourly_rate_snapshot;}).toBe(1900.01);
 await lesson.click({button:"right"});await page.getByRole("menuitem",{name:"Личное",exact:true}).click();await page.getByLabel("Ставка, ₽/час",{exact:true}).fill("2500");await page.getByRole("button",{name:"Сохранить",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);expect((await(await request.get(fixture+"/state")).json()).lessons[0].hourly_rate_snapshot).toBe(1900.01);
});
test("018 owner GIF background persists, delegated admin sees it, offset and grid appearance",async({page,browser})=>{
 await login(page);await expect(page.locator(".schedule-time-labels span").last()).toHaveText("00:00");await page.locator(".schedule-grid").focus();expect(await page.locator(".schedule-grid").evaluate(el=>getComputedStyle(el).outlineStyle)).toBe("none");
 const offset=page.getByLabel("Сдвиг МСК",{exact:true});await offset.fill("2.5");await offset.press("Enter");await expect(offset).toHaveValue("0");await offset.fill("2");await offset.press("Enter");await expect(offset).toHaveValue("+2");
 await page.getByRole("button",{name:"Фон",exact:true}).click();await page.getByLabel("Загрузить / заменить").setInputFiles({name:"background.gif",mimeType:"image/gif",buffer:Buffer.from("R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","base64")});await expect(page.locator(".background-preview")).toBeVisible();await expect(page.getByText("Фон сохранён.",{exact:true})).toBeVisible();await page.keyboard.press("Escape");await page.reload();await expect(page.locator(".schedule-background img")).toBeVisible();await expect(offset).toHaveValue("+2");
 await page.locator(".schedule-lesson").first().click({button:"right"});await expect(page.getByRole("menuitem",{name:"Личное",exact:true})).toHaveCount(0);await page.keyboard.press("Escape");
 const admin=await browser.newPage();try{await login(admin,"admin");await admin.goto(`/admin/schedule?tutor=${tutor}`);await expect(admin.locator(".schedule-background img")).toBeVisible();await expect(admin.getByRole("button",{name:"Фон",exact:true})).toHaveCount(0);await expect(admin.getByLabel("Сдвиг МСК",{exact:true})).toBeDisabled();}finally{await admin.close();}
 await page.screenshot({path:"artifacts/018-background.png",fullPage:true});await page.getByRole("button",{name:"Фон",exact:true}).click();await page.getByRole("button",{name:"Удалить фон",exact:true}).click();await expect(page.locator(".background-preview")).toHaveCount(0);
});
test("018 rich document preview, lists, math, code, copy and draft history survive reload",async({page,context,request})=>{
 await context.grantPermissions(["clipboard-read","clipboard-write"]);await login(page);await page.goto(`/tutor/chats?student=${student}`);const input=page.getByLabel("Сообщение ученику",{exact:true});await expect(input).toHaveAttribute("contenteditable","true");await input.focus();
 await input.evaluate(el=>{const data=new DataTransfer();data.setData("text/html",'<p style="text-align:center"><b>Формула</b> $x^2$</p><ol><li>Первый</li><li>Второй</li></ol><pre><code class="language-js">  const x = "&lt;x&gt;";\n</code></pre>');el.dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:data}));});
 await expect(page.locator(".chat-live-preview .katex")).toBeVisible();await expect(page.locator(".chat-live-preview ol li")).toHaveCount(2);await page.getByRole("button",{name:"Отменить",exact:true}).click();await expect(input).toHaveText("");await page.getByRole("button",{name:"Вернуть",exact:true}).click();await expect(input).toContainText("Формула");await page.getByRole("button",{name:"Отправить",exact:true}).click();await expect(page.locator(".chat-bubble .katex")).toBeVisible();await page.reload();await expect(page.locator(".chat-bubble ol li")).toHaveCount(2);await expect(page.locator(".chat-bubble pre")).toHaveText('  const x = "<x>";\n');await page.locator(".chat-bubble").getByRole("button",{name:"Копировать",exact:true}).click();await expect.poll(()=>page.evaluate(async()=>(await navigator.clipboard.readText()).replace(/\r\n/g,"\n"))).toBe('  const x = "<x>";\n');
 const sent=(await(await request.get(fixture+"/applications-state")).json()).messages.find((m:{rich_message?:unknown})=>m.rich_message);
 expect(sent.rich_message.blocks.some((b:{type:string})=>b.type==="table")).toBe(true);expect(JSON.stringify(sent.rich_message)).toContain('"mathematical_expression"');expect(sent.reply_markup.inline_keyboard[0][0].callback_data).toMatch(/^chat:reply:/);
 await page.screenshot({path:"artifacts/018-rich-chat.png",fullPage:true});
});
test("018 Telegram GIF and all sticker kinds use their web renderers",async({page,request})=>{
 await login(page);await page.goto(`/tutor/chats?student=${student}`);
 const webp=Buffer.from(await page.evaluate(()=>{const c=document.createElement("canvas");c.width=c.height=20;return [...Uint8Array.from(atob(c.toDataURL("image/webp").split(",")[1]),x=>x.charCodeAt(0))];}));
 const webm=Buffer.from(await page.evaluate(async()=>{const c=document.createElement("canvas");c.width=c.height=20;const stream=c.captureStream(10),recorder=new MediaRecorder(stream,{mimeType:"video/webm"});const chunks:Blob[]=[];recorder.ondataavailable=e=>chunks.push(e.data);const done=new Promise<Blob>(resolve=>{recorder.onstop=()=>resolve(new Blob(chunks));});recorder.start();c.getContext("2d")!.fillRect(0,0,20,20);await new Promise(resolve=>setTimeout(resolve,250));recorder.stop();const blob=await done;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await blob.arrayBuffer())];}));
 const tgs=gzipSync(JSON.stringify({v:"5.5.0",fr:30,w:512,h:512,ip:0,op:60,layers:[]}));
 const send=(data:unknown)=>request.post("/api/telegram/webhook",{headers:{"x-telegram-bot-api-secret-token":"fixture-webhook"},data});
 const cases=[{bytes:Buffer.from("R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","base64"),media:{animation:{file_id:"gif"}},selector:".chat-image-preview img"},{bytes:webp,media:{sticker:{file_id:"webp",width:20,height:20}},selector:".chat-sticker img"},{bytes:tgs,media:{sticker:{file_id:"tgs",width:512,height:512,is_animated:true}},selector:".chat-sticker svg"},{bytes:webm,media:{sticker:{file_id:"webm",width:20,height:20,is_video:true}},selector:".chat-sticker video"}];
 for(const [i,c] of cases.entries()){await request.post(fixture+"/telegram-file",{data:{base64:c.bytes.toString("base64")}});await send({update_id:180000+i*2,callback_query:{id:`choose${i}`,from:{id:100004},message:{message_id:1,chat:{id:100004,type:"private"}},data:`chat:to:${tutor}`}});const result=await send({update_id:180001+i*2,message:{message_id:180100+i,from:{id:100004},chat:{id:100004,type:"private"},...c.media}});expect(result.ok()).toBe(true);await expect(page.locator(c.selector).last()).toBeVisible({timeout:12000});if(i>0)await expect(page.locator(c.selector).last().locator("xpath=ancestor::article").locator(".chat-file-row")).toHaveCount(0);}
});
